platform :ios, '9.0'

target 'konfswift' do
  use_frameworks!

  # Pods for konfswift
  pod 'SDWebImage', '~> 4.1.0'

  target 'konfswiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
